<html>
    <head>
        <title>codevated.com</title>
		<!-- App css -->
		<link rel="stylesheet" href="css/design.css">
		
		<link rel="shortcut icon" href="" />
		
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

		<!-- jQuery library -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

		<!-- Latest compiled JavaScript -->
		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>	
		
		<script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>	
		<style>
			header{
				display:none;
			}
			footer{
				border-top:#E8E8E8 0.1em solid;				
				width:100%;
				padding:7px;
				font-size:12px;
				margin-top:5%;
			}
			footer p{
				margin-bottom:0px;
				margin-top:5px;
				text-align:center;
			}
			footer ul{
				list-style:none;
				margin-bottom:0px;
				margin-top:0px;
			}
			footer li{
				display:inline;
				margin-left:1%;
				text-align:center;
			}
			footer li a{
				font-weight:600;
				color:#515251;
			}
		</style>
		
		</head>
    <body>
		<header>			
			<div class="top-menu-bar">
				<div class="logo">
					<img src="img/logo.png"/>
				</div>
			</div>
		</header>
		<div class="content">		
