<div class="clear">	
</div>
	<footer>
		<div class="bottom-color-bar">
			www.codevated.com | Learn from mentorship & apprenticeship
		</div>
		<p>
		<ul>
			<li><a href="">About</a></li>
			<li><a href="">Contact codevated</a></li>
			<li><a href="">Terms</a></li>
			<li><a href="">Privacy</a></li>
			<li><a href="">Help</a></li>
			<div class="clear"></div>
		</ul>	
		</p> 
		<p>&copy; 2017 Codevated.com, inc </p> 
	</footer>
</div>
</body>
</html>